### ISSUE TITLE
Does it break with agave for compatibility ?!

### ISSUE THREAD

**Issue by jun0tpyrc** [c29r3/solana-snapshot-finder#22]
https://github.com/anza-xyz/agave 1.8.25

tried multiple times, still can't use the snapshots downloaded by this
```
[2024-10-14T00:54:50.678556142Z INFO  solana_runtime::snapshot_bank_utils] Loading bank from full snapshot archive: /data/ledger/snapshot-295456046-35iw4vsMuLsRN81wrms3G2iKRwmhuzXAHpwjW79
YVs3d.tar.zst, and incremental snapshot archive: Some("/data/ledger/incremental-snapshot-295456046-295480946-7fe9JJ3WPSjfgZyUSsSdmDbbFWjza59qMMuMaGBzZMFW.tar.zst")
thread 'solUnpkSnpsht02' panicked at /var/lib/buildkite-agent/builds/release/anza/agave-secondary/accounts-db/src/hardened_unpack.rs:338:45:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
stack backtrace:
thread 'solUnpkSnpsht00' panicked at /var/lib/buildkite-agent/builds/release/anza/agave-secondary/accounts-db/src/hardened_unpack.rs:338:45:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
thread 'solUnpkSnpsht03' panicked at /var/lib/buildkite-agent/builds/release/anza/agave-secondary/accounts-db/src/hardened_unpack.rs:338:45:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
thread 'solUnpkSnpsht01' panicked at /var/lib/buildkite-agent/builds/release/anza/agave-secondary/accounts-db/src/hardened_unpack.rs:338:45:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: solana_accounts_db::hardened_unpack::unpack_snapshot_with_processors
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
[2024-10-14T00:54:53.255830081Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solUnpkSnpsht02" one=1i message="panicked at /var/lib/buildkite-agent/builds/re
lease/anza/agave-secondary/accounts-db/src/hardened_unpack.rs:338:45:
    called `Result::unwrap()` on an `Err` value: \"SendError(..)\"" location="/var/lib/buildkite-agent/builds/release/anza/agave-secondary/accounts-db/src/hardened_unpack.rs:338:45" versi
on="1.18.25 (src:92ddaa20; feat:3241752014, client:Agave)"
```

**Comment by c29r3** [comment]
Some versions of Solana client may not be compatible with each other. Try filtering the snapshot search by the same version that you currently have installed. I haven't been a Solana validator for a long time and I don't have my own node to check this
You can try this flag
`--version VERSION     search for a snapshot from a specific version node `

If it does not work, you can search some RPC compatible with your client version and download it manualy (with wget, for example) — https://solana.rpc-finder.com/
`wget  --trust-server-names http://{NODE_IP}:8899/genesis.tar.bz2 -O{LEDGER_FOLDER_PATH}`
